//! Embeds the application icon into the executable.
//!
//! Windows takes its icon from a resource compiled into the binary, not from a
//! file beside it — so unlike the Apple bundles there is nowhere to simply drop
//! a PNG. `openflow.ico` is generated by `../tools/make-icons.sh` from the same
//! drawing the Mac and iOS icons come from, and committed, because that script
//! needs macOS tooling that does not exist on the machine this crate is built
//! on.

fn main() {
    println!("cargo:rerun-if-changed=openflow.ico");

    #[cfg(windows)]
    {
        let mut res = winresource::WindowsResource::new();
        res.set_icon("openflow.ico");
        res.set("ProductName", "OpenFlow");
        res.set("FileDescription", "OpenFlow dictation");
        if let Err(e) = res.compile() {
            // Not fatal. A binary with no icon still works, and failing the
            // whole build over decoration would be the wrong trade.
            println!("cargo:warning=could not embed the icon: {e}");
        }
    }
}
